<?xml version="1.0"?>
<sdf version="1.8" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Gerando o SDF:
        $ xacro arena_paredes.sdf.xacro > arena_paredes.sdf
     -->

    <!-- Parâmetros globais -->
    <xacro:property name="gp_w" value="100.0"/>
    <xacro:property name="gp_h" value="100.0"/>

    <!-- Bases -->
    <xacro:property name="base_w" value="6"/>
    <xacro:property name="base_l" value="8"/>
    <xacro:property name="base_h" value="0.01"/>
    <xacro:property name="base_offset" value="3"/>

    <!-- Arena -->
    <xacro:property name="pos_x" value="0"/>
    <xacro:property name="pos_y" value="0"/>
    <xacro:property name="pos_z" value="0"/>
    <xacro:property name="altura"      value="0.5"/>
    <xacro:property name="espessura"   value="0.1"/>
    <xacro:property name="comprimento" value="${ (base_w+base_offset+espessura) * 2 }"/>
    <xacro:property name="largura"     value="${ base_l + (espessura * 2)}"/>
    <xacro:property name="cor"         value="0.5 0.5 0.5 1"/>

    <!-- Centro -->
    <xacro:property name="raio_centro" value="0.5"/>

    <!-- Bandeira -->
    <xacro:property name="flag_z"            value="0.2"/>     <!-- altura da base da bandeira -->
    <xacro:property name="flag_rot"          value="1.5708"/>  <!-- rotação em Z -->
    <xacro:property name="flag_pole_radius"  value="0.03"/>
    <xacro:property name="flag_pole_length"  value="0.4"/>
    <xacro:property name="flag_panel_size"   value="0.3 0.01 0.2"/>
    <xacro:property name="flag_panel_pose"   value="0.16 0 0.38 0 0 0"/>
    <xacro:property name="flag_base_radius" value="0.05"/>
    <xacro:property name="flag_base_thickness" value="0.01"/>

    <xacro:macro name="bandeira" params="name x y z rot cor label">

        <model name="${name}">
            <static>false</static>

            <plugin filename="ignition-gazebo-label-system" name="ignition::gazebo::systems::Label">
                <label>${label}</label>
            </plugin>

            <link name="${name}_link">
                <pose>${x} ${y} ${z} 0 0 ${rot}</pose>

                <!-- Mastro -->
                <visual name="pole_visual">
                    <pose>0 0 ${flag_pole_length/2} 0 0 0</pose>
                    <geometry>
                    <cylinder>
                        <radius>${flag_pole_radius}</radius>
                        <length>${flag_pole_length}</length>
                    </cylinder>
                    </geometry>
                    <material>
                        <ambient>0.2 0.2 0.2 1</ambient>
                        <diffuse>0.3 0.3 0.3 1</diffuse>
                    </material>
                </visual>

                <!-- Painel da bandeira -->
                <visual name="${name}_panel_visual">
                    <pose>${flag_panel_pose}</pose>
                    <geometry>
                    <box>
                        <size>${flag_panel_size}</size>
                    </box>
                    </geometry>
                    <material>
                    <ambient>${cor}</ambient>
                    <diffuse>${cor}</diffuse>
                    </material>
                </visual>

                <!-- Colisão -->
                <collision name="${name}_collision">
                    <pose>0 0 ${flag_pole_length/2} 0 0 0</pose>
                    <geometry>
                    <box>
                        <size>${flag_pole_radius*2} ${flag_pole_radius*2} ${flag_pole_length} </size>
                    </box>
                    </geometry>
                </collision>

                <!-- Base da bandeira (visual) -->
                <visual name="base_visual">
                    <pose>0 0 ${flag_base_thickness/2} 0 0 0</pose>
                    <geometry>
                        <cylinder>
                        <radius>${flag_base_radius}</radius>
                        <length>${flag_base_thickness}</length>
                        </cylinder>
                    </geometry>
                    <material>
                        <ambient>0.1 0.1 0.1 1</ambient>
                        <diffuse>0.2 0.2 0.2 1</diffuse>
                    </material>
                </visual>

                <!-- Base da bandeira (colisão) -->
                <collision name="base_collision">
                    <pose>0 0 ${flag_base_thickness/2} 0 0 0</pose>
                    <geometry>
                        <box>
                            <size>${flag_base_radius*2} ${flag_base_radius*2} ${flag_base_thickness} </size>
                        </box>
                    </geometry>
                </collision>


                <collision name="top_base_collision">
                    <pose>0 0 ${flag_pole_length*0.75} 0 0 0</pose>
                    <geometry>
                        <box>
                            <size>${flag_base_radius*2} ${flag_base_radius*2} ${flag_base_thickness} </size>
                        </box>
                    </geometry>
                </collision>

                <!-- Inércia -->
                <inertial>
                    <mass>0.1</mass>
                    <inertia>
                    <ixx>0.001</ixx>
                    <iyy>0.001</iyy>
                    <izz>0.001</izz>
                    </inertia>
                </inertial>
            </link>
        </model>

    </xacro:macro>

    <world name='capture_the_flag_world'>

        <plugin name='ignition::gazebo::systems::Physics' filename='ignition-gazebo-physics-system'/>
        <plugin name='ignition::gazebo::systems::UserCommands' filename='ignition-gazebo-user-commands-system'/>
        <plugin name='ignition::gazebo::systems::SceneBroadcaster' filename='ignition-gazebo-scene-broadcaster-system'/>
        
        <plugin filename="ignition-gazebo-sensors-system" name="ignition::gazebo::systems::Sensors">
            <render_engine>ogre2</render_engine>
        </plugin>
        
        <plugin filename="libignition-gazebo-contact-system.so" name="ignition::gazebo::systems::Contact">
        </plugin>

        <scene>
            <ambient>1.0 1.0 1.0</ambient>
            <background>0.8 0.8 0.8</background>
        </scene>

        <light name="sun" type="directional">
            <cast_shadows>true</cast_shadows>
            <pose>0 0 10 0 0 0</pose>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.2 0.2 0.2 1</specular>
            <attenuation>
                <range>1000</range>
                <constant>0.9</constant>
                <linear>0.01</linear>
                <quadratic>0.001</quadratic>
            </attenuation>
            <direction>-0.5 0.1 -0.9</direction>
        </light>

        <model name='ground_plane'>
            <static>1</static>
            <self_collide>0</self_collide>
            <enable_wind>0</enable_wind>
            <kinematic>0</kinematic>

            <plugin filename="ignition-gazebo-label-system" name="ignition::gazebo::systems::Label">
                <label>5</label>
            </plugin>

            <link name='ground_plane_link'>
                <collision name='ground_plane_collision'>
                <geometry>
                    <plane>
                    <normal>0 0 1</normal>
                    <size>${gp_w} ${gp_h}</size>
                    </plane>
                </geometry>

                </collision>
                <visual name='ground_plane_visual'>
                <cast_shadows>0</cast_shadows>
                <geometry>
                    <plane>
                    <normal>0 0 1</normal>
                    <size>${gp_w} ${gp_h}</size>
                    </plane>
                </geometry>

                <material>
                    <ambient>0.94 0.90 0.81 1</ambient>
                    <diffuse>0.94 0.90 0.81 1</diffuse>
                    <specular>1 1 1 0</specular>
                </material>

                </visual>
            </link>
        </model>

        <model name='red_base'>
            <pose>${-(base_w/2.0+base_offset)} 0 0 0 0 0</pose>
            <self_collide>0</self_collide>
            <enable_wind>0</enable_wind>
            <kinematic>0</kinematic>
            <static>1</static>

            <plugin filename="ignition-gazebo-label-system" name="ignition::gazebo::systems::Label">
                <label>10</label>
            </plugin>

            <link name='red_base_link'>
                <collision name='red_base_collision'>
                    <geometry>
                        <box>
                            <size>${base_w} ${base_l} ${base_h}</size>
                        </box>
                    </geometry>
                </collision>
                <visual name='red_base_visual'>
                    <geometry>
                        <box>
                            <size>${base_w} ${base_l} ${base_h}</size>
                        </box>
                    </geometry>
                    <material>
                        <ambient>1 0 0 1</ambient>
                        <diffuse>1 0 0 1</diffuse>
                    </material>
                </visual>
            </link>
        </model>

        <model name='blue_base'>
            <pose>${(base_w/2.0+base_offset)} 0 0 0 0 0</pose>
            <static>1</static>
            <self_collide>0</self_collide>
            <enable_wind>0</enable_wind>
            <kinematic>0</kinematic>

            <plugin filename="ignition-gazebo-label-system" name="ignition::gazebo::systems::Label">
                <label>15</label>
            </plugin>

            <link name='blue_base_link'>

                <collision name='blue_base_collision'>
                <geometry>
                    <box>
                    <size>${base_w} ${base_l} ${base_h}</size>
                    </box>
                </geometry>
                </collision>

                <visual name='blue_base_visual'>
                <geometry>
                    <box>
                    <size>${base_w} ${base_l} ${base_h}</size>
                    </box>
                </geometry>
                <material>
                    <ambient>0 0 1 1</ambient>
                    <diffuse>0 0 1 1</diffuse>
                </material>
                </visual>

            </link>
        </model>

        <!-- Bandeira vermelha -->
        <xacro:bandeira
        name="red_flag"
        x="${-(base_offset+base_w-1.0)}"
        y="0"
        z="${flag_z}"
        rot="${flag_rot}"
        cor="1 0 0 1"
        label="20" />

        <!-- Bandeira azul -->
        <xacro:bandeira
        name="blue_flag"
        x="${(base_offset+base_w-1.0)}"
        y="0"
        z="${flag_z}"
        rot="${flag_rot}"
        cor="0 0 1 1"
        label="25" />

        <model name='center_zone'>
            <pose>0 0 0 0 0 0</pose>
            <static>1</static>
            <self_collide>0</self_collide>
            <enable_wind>0</enable_wind>
            <kinematic>0</kinematic>

            <plugin filename="ignition-gazebo-label-system" name="ignition::gazebo::systems::Label">
                <label>30</label>
            </plugin>

            <link name='center_zone_link'>
                <collision name='center_zone_collision'>
                <geometry>
                    <cylinder>
                    <radius>0.5</radius>
                    <length>0.01</length>
                    </cylinder>
                </geometry>
                <max_contacts>10</max_contacts>
                </collision>
                <visual name='center_zone_visual'>
                <geometry>
                    <cylinder>
                    <radius>0.5</radius>
                    <length>0.01</length>
                    </cylinder>
                </geometry>
                <material>
                    <ambient>1 1 0 1</ambient>
                    <diffuse>1 1 0 1</diffuse>
                </material>
                </visual>
            </link>
        </model>

        <model name='flag_deploy_zone'>
            <pose>-8 -0.5 0.01 0 0 0</pose>
            <static>1</static>
            <self_collide>0</self_collide>
            <enable_wind>0</enable_wind>
            <kinematic>0</kinematic>

            <plugin filename="ignition-gazebo-label-system" name="ignition::gazebo::systems::Label">
                <label>28</label>
            </plugin>

            <link name='flag_deploy_zone_link'>
                <collision name='flag_deploy_zone_collision'>
                <geometry>
                    <cylinder>
                    <radius>0.5</radius>
                    <length>0.01</length>
                    </cylinder>
                </geometry>
                <max_contacts>10</max_contacts>
                </collision>
                <visual name='flag_deploy_zone_visual'>
                <geometry>
                    <cylinder>
                    <radius>0.5</radius>
                    <length>0.01</length>
                    </cylinder>
                </geometry>
                    <material>
                    <ambient>0 1 0 1</ambient>
                    <diffuse>0 1 0 1</diffuse>
                    </material>
                </visual>
            </link>
        </model>

        <model name="paredes_arena">
            <pose>${pos_x} ${pos_y} ${pos_z} 0 0 0</pose>

            <plugin filename="ignition-gazebo-label-system" name="ignition::gazebo::systems::Label">
            <label>35</label>
            </plugin>

            <!-- Parede inferior -->
            <link name="parede_lateral_inferior">
            <pose>0 ${-largura/2} 0 0 0 0</pose>
            <collision name="col">
                <pose>0 0 ${altura/2} 0 0 0</pose>
                <geometry>
                <box><size>${comprimento} ${espessura} ${altura}</size></box>
                </geometry>
            </collision>
            <visual name="vis">
                <pose>0 0 ${altura/2} 0 0 0</pose>
                <geometry>
                <box><size>${comprimento} ${espessura} ${altura}</size></box>
                </geometry>
                <material>
                <ambient>${cor}</ambient>
                <diffuse>${cor}</diffuse>
                    <specular>0.1 0.1 0.1 1</specular>
                </material>
            </visual>
            </link>

            <!-- Parede superior -->
            <link name="parede_lateral_superior">
            <pose>0 ${largura/2} 0 0 0 3.14159</pose>
            <collision name="col">
                <pose>0 0 ${altura/2} 0 0 0</pose>
                <geometry>
                <box><size>${comprimento} ${espessura} ${altura}</size></box>
                </geometry>
            </collision>
            <visual name="vis">
                <pose>0 0 ${altura/2} 0 0 0</pose>
                <geometry>
                <box><size>${comprimento} ${espessura} ${altura}</size></box>
                </geometry>
                <material>
                <ambient>${cor}</ambient>
                <diffuse>${cor}</diffuse>
                <specular>0.1 0.1 0.1 1</specular>
                </material>
            </visual>
            </link>

            <!-- Parede direita -->
            <link name="parede_fundo_blue">
            <pose>${comprimento/2} 0 0 0 0 1.5708</pose>
            <collision name="col">
                <pose>0 0 ${altura/2} 0 0 0</pose>
                <geometry>
                <box><size>${largura} ${espessura} ${altura}</size></box>
                </geometry>
            </collision>
            <visual name="vis">
                <pose>0 0 ${altura/2} 0 0 0</pose>
                <geometry>
                <box><size>${largura} ${espessura} ${altura}</size></box>
                </geometry>
                <material>
                <ambient>${cor}</ambient>
                <diffuse>${cor}</diffuse>
                <specular>0.1 0.1 0.1 1</specular>
                </material>
            </visual>
            </link>

            <!-- Parede esquerda -->
            <link name="parede_fund_red">
            <pose>${-comprimento/2} 0 0 0 0 -1.5708</pose>
            <collision name="col">
                <pose>0 0 ${altura/2} 0 0 0</pose>
                <geometry>
                <box><size>${largura} ${espessura} ${altura}</size></box>
                </geometry>
            </collision>
            <visual name="vis">
                <pose>0 0 ${altura/2} 0 0 0</pose>
                <geometry>
                <box><size>${largura} ${espessura} ${altura}</size></box>
                </geometry>
                <material>
                <ambient>${cor}</ambient>
                <diffuse>${cor}</diffuse>
                <specular>0.1 0.1 0.1 1</specular>
                </material>
            </visual>
            </link>

        </model>

        <include>
            <uri>Paredes</uri>
            <name>obstaculos_vermelho</name>
            <pose>-6 0 0.0 0 0 0</pose>
            <!-- Defefinindo label de obstaculos como 30 -->    
            <plugin name="ignition::gazebo::systems::Label" filename="ignition-gazebo-label-system">
                <label>30</label>
            </plugin>
        </include>

        <include>
            <uri>Paredes</uri>
            <name>obstaculos_azul</name>
            <pose>6 0 0 0 0 3.141592654</pose>
            <!-- Defefinindo label de obstaculos como 30 -->    
            <plugin name="ignition::gazebo::systems::Label" filename="ignition-gazebo-label-system">
                <label>30</label>
            </plugin>
        </include>


    </world>
</sdf>